<?php
	require_once("database.php"); //panggil file database.php
	
	/*
	* Pengaturan Website Ada di file setting.php
	* Code Generated by  Andi Sholihin - dieka.91@gmail.com
	* http://sekedar-tutorial.blogspot.com
	*/
	
	//memanggil pengaturan dari database
	$query = mysql_query("SELECT * FROM setting");
	
	if ($query) {
		$set = mysql_fetch_array($query);
		
		$judul_web = $set['judul_web'];
		
		$deskripsi = $set['deskripsi_web'];
		
		$email_admin = $set['email_admin'];
		
		$url_web = $set['url_web'];
		
		$maintenance = $set['maintenance'];
		
		$tgl_setting = $set['tgl_setting'];
		
		$telpon = $set['telpon'];
		
		$alamat = $set['alamat'];
		
		$maintenance = $set['maintenance'];
	}
?>